apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        hostPath:
          path: /data/db
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: app-v2
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
