apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGO_USER: {{ .Values.mongo.secret.user }}
  MONGO_PASSWORD: {{ .Values.mongo.secret.password }}
